apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw
  namespace: argocd
spec:
  project: default
  source:
    chart: openclaw
    repoURL: https://serhanekicii.github.io/openclaw-helm
    targetRevision: 1.5.15 # Use the latest version
    helm:
      values: |
        app-template:
          controllers:
            main:
              containers:
                main:
                  envFrom:
                    - secretRef:
                        name: openclaw-env-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: openclaw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
