apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  finalizers:
    - kubevirt.io/virtualMachineControllerFinalize
  name: centos-dv
  namespace: vms
spec:
  dataVolumeTemplates:
    - metadata:
        name: centos-dv-root
      spec:
        source:
          registry:
            url: docker://quay.io/containerdisks/centos-stream:9
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: local-path
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        kubevirt.io/pci-topology-version: v3
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinit
          interfaces:
            - masquerade: {}
              name: default
          rng: {}
        firmware:
          serial: 87dcf8b7-04ee-43e7-9d23-2a6536c6f9f2
          uuid: eb319f7a-b61f-4812-9c3f-fb57e0697c36
        machine:
          type: q35
        memory:
          guest: 2Gi
        resources: {}
      networks:
        - name: default
          pod: {}
      nodeSelector:
        swipe-lab/virt: "true"
      volumes:
        - dataVolume:
            name: centos-dv-root
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: swipelab
              chpasswd:
                expire: false
          name: cloudinit
