apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://otwld.github.io/ollama-helm
    chart: ollama
    targetRevision: "*"
    helm:
      valuesObject:
        ollama:
          gpu:
            enabled: true
            type: nvidia
            number: 1
          models:
            - gemma4:31b
        persistentVolume:
          enabled: true
          size: 50Gi
        nodeSelector:
          kubernetes.io/hostname: swipe-worker-3
        resources:
          limits:
            nvidia.com/gpu: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
